### PR TITLE
Nightly

### PR DESCRIPTION
**Pull request by dlech**

### CODE REVIEW

**Comment by WasabiFan** [comment]
What's happening with that Gitter commit? Wasn't it already merged? (Might this be a squashing issue?)

**Comment by dlech** [comment]
yeah, I actually cherry picked the new commit here and pushed it already.

**Comment by WasabiFan** [comment]
I was just wondering what had hppened; how was the other commit re-written?

**Comment by dlech** [comment]
Since I used the squash and merge feature of github when I "merged" the gitter commit, it created a new commit on github that was different from the one on my local machine. Both commits have the same changes, which is why you don't see it in the diff on this pull request.

**Pull request closed without merging**
