### PR TITLE
Fixed broken link

### PR DESCRIPTION
**Pull request by mattruzzi**
Changed mindstorms.lego.com to lego.com/mindstorms

### CODE REVIEW

**Comment by dlech** [comment]
Thanks. Although EV3 is retiring soon, so maybe we should pick another link that will have something about EV3 for longer in the future?

**Comment by mattruzzi** [comment]
Should we link directly to the ev3 set page?  <https://www.lego.com/product/lego-mindstorms-ev3-31313>
There also is a [different link for the education edition](https://education.lego.com/products/lego-mindstorms-education-ev3-core-set/5003400), so we could also make the model numbers below link to the page for that model number.

**Comment by dlech** [comment]
I think linking to the LEGO Education site sounds like a good idea. It is hard to say how long the link for the 31313 set will be around after the new MINDSTORMS comes out.

**Comment by dlech** [comment]
merged, thanks!

**Pull request merged**
