### PR TITLE
EV3-Robot-Demo

### PR DESCRIPTION
**Pull request by EyeTreasure**
Kindly add this to the Project Website. It will help a lot of people to get their robot up and running easily.

### CODE REVIEW

**Comment by dlech** [comment]
It looks like you have deleted our example page. There are also some things left over from the example page that need to be deleted from your new page. Can you please fix those things?

**Comment by EyeTreasure** [comment]
Sorry I was wondering where the example page has gone. I could not find any
example page this time so I simply recycled my first version from last
year. If I should have deleted it inadvertently it would have occured last
year but I thought Gihub provides only copies so originals cannot get
deleted anyway? I am new to Github and I hope I have not caused any problem
here. Kindly talk me through the procedure to get things sorted.

Best regards

Berend

**Comment by dlech** [comment]
It might be easiest to click the "Create New File" button on [this page](https://github.com/ev3dev/ev3dev.github.io/tree/master/projects/_posts) and copy and past what you have here into the new page and create a new pull request.

**Comment by WasabiFan** [comment]
I just opened https://github.com/EyeTreasure/ev3dev.github.io/pull/2 to make the mentioned changes; @EyeTreasure you can just merge that instead of manually re-adding the file.

**Comment by WasabiFan** [comment]
Dammit, I got it wrong too 😦

**Comment by EyeTreasure** [comment]
Thanks for trying....

**Comment by WasabiFan** [comment]
Thanks @EyeTreasure!

**Comment by WasabiFan** [comment]
The page is live here: http://www.ev3dev.org/projects/2017/03/20/Community-EV3-Python-Demo-for-Mac/

**Comment by EyeTreasure** [comment]
Great job. Thanks.

**Pull request merged**
