### PR TITLE
ev3dev-jessie-2016-12-21 announcemnt

### PR DESCRIPTION
**Pull request by dlech**

### CODE REVIEW

**Comment by WasabiFan** [comment]
@JorgePe Is `http://ofalcao.pt/` your site? If so, it seems to be having issues with its _base de dados_ 🤣

**Comment by dlech** [comment]
I left you the `e` because the announcement is so short. Just kidding. I just made that up.

**Comment by JorgePe** [comment]
@WasabiFan yeap... everytime someone finds my site, mysql goes down. I need to tune it better or give up wordpress. Thanks.

**Comment by WasabiFan** [comment]
Haha sorry about that... I suppose us linking to a site is pretty much the equivalent of a DOS attack for small set-ups. If it would be helpful, we can whitelist your site so that our builds just assume that those links are valid.

**Comment by JorgePe** [comment]
The whitelist would be great now... this morning I updated my VPS to a more recente ubuntu version without noticing a major mysql upgrade... now my wordpress blog is down, I'm waiting for service desk to restore a previous backup.

**Pull request merged**
