### PR TITLE
Added Pathfind3r project info.

### PR DESCRIPTION
**Pull request by okanulas**

### CODE REVIEW

**Comment by WasabiFan** [comment]
This is one of the best examples I've seen of system integration on ev3dev (and it has a cool UI as well!). Am I correct in my understanding from your repo that you have both a PHP app and a Python script running on the EV3? Or is it offloading processing work to a PC?

P.S. Don't worry about the "all checks have failed" message; other pages are having issues, not yours. @dlech will take a look at your PR when he has the time.

**Comment by rhempel** [comment]
Hey, that's pretty cool - believe it or not, I did something similar with my old LEGO RCX - in FORTH :-) Nice job!

**Comment by dlech** [comment]
Super! Thanks for sharing.

**Comment by okanulas** [comment]
Hi all. Sorry for the delay. It has been a busy day.

I'm glad that you liked it and thanks for providing ev3dev. i would be happy to help if you have questions or problems about the project.

@WasabiFan > Apache Server, php, python, everything is running on ev3. Pc is only providing internet connection to the brick. When you open the ev3's ip address with your browser from your pc, webserver directs you to the web control page. it is very useful especially when you testing the code with different parameters. 

@rhempel Thanks. I made some little designs for learning the basics for both hardware and software but this is my first "real" project. I hope to find more time to improve pathfind3r and develop new things.

@dlech Thanks. You're welcome.

**Pull request merged**
