### PR TITLE
Created Congkak Robot post

### PR DESCRIPTION
**Pull request by jimmyasyraf**
A post about my congkak robot project.

### CODE REVIEW

**Comment by WasabiFan** [comment]
Cool robot!

The main issue that I see is that the thumbnail URL points to the GitHub web page that includes the image instead of the image itself. To fix this, you can either switch the URL to be a link to the actual `.jpg` (`https://github.com/jimmyasyraf/congkak-robot/raw/master/CqNqS9HUAAAI-Qq.jpg`) or you can add the image file directly to this repository under the `images/projects/` directory. I would prefer the latter option, so that all the site content is together, but I don't think it's a big issue either way. You can upload files using the "Upload files" button on the GitHub page or with git locally if you are comfortable with it.

Also, the page looks a bit empty as-is. You can display the thumbnail image on the page itself as well using this code right before your text:

```handlebars
{% include screenshot.html source=page.thumbnail_override width="100%" %}
```

**Comment by WasabiFan** [comment]
Also, ignore the CI server build error. That's not related to your page.

**Comment by dlech** [comment]
You now have two project pages for the same project. Please delete the old one.

**Comment by WasabiFan** [comment]
This looks good to me; I'll merge it now.

Thanks for the project page @jimmyasyraf!

**Comment by WasabiFan** [comment]
The page is live at http://www.ev3dev.org/projects/2016/08/23/Congkak-Robot/.

**Comment by bmegli** [comment]
@jimmyasyraf The robot is awesome!

You can embedd your youtube video if you like and/or add other authors (if without github, then without @):

```
---
author: [ "@jimmyasyraf", "Harun Idris", "Eddie Puah" ] 

programming_language: "Python" # The programming language used in this project

youtube_video_id: dwgcK0PYnWk
thumbnail_override: "https://github.com/jimmyasyraf/congkak-robot/raw/master/CqNqS9HUAAAI-Qq.jpg" # If you don't have a YouTube video (or the video thumbnail isn't good) you can uncomment this line to set your own image for the project. 

project_homepage_url: "https://github.com/jimmyasyraf/congkak-robot/" # Homepage for this project
source_code_url: "https://github.com/jimmyasyraf/congkak-robot/" # Provide a link to your code
---
```

You may also want to not include the nice image then or move it to the bottom so that it's not right below the embedded youtube video.

**Comment by WasabiFan** [comment]
@bmegli I think @jimmyasyraf didn't have a video at the time that this page was created. Did you find one that has been created since then?

**Comment by bmegli** [comment]
@WasabiFan 

> @bmegli I think @jimmyasyraf didn't have a video at the time that this page was created. Did you find one that has been created since then?

Yes! This is even the one I gave in the code snippet above, 4 days old:

https://www.youtube.com/watch?v=dwgcK0PYnWk

**Pull request merged**
