### PR TITLE
Add docker cross-compiler info

### PR DESCRIPTION
**Pull request by dlech**

### CODE REVIEW

**Comment by WasabiFan** [comment]
Just curious: why do you specify PowerShell instead of CMD? I've used both with Docker and there aren't any differences as far as I can tell, aside from the fact that pasting is a different menu.

**Comment by dlech** [comment]
Because I don't know what I'm doing. :wink:

**Comment by WasabiFan** [comment]
Oh, ok :laughing:. It isn't a problem -- I was just wondering if there was something I had missed.

**Comment by WasabiFan** [comment]
> We think you will have a whale of a good time.

😆 :+1:

**Comment by dlech** [comment]
I had to make sure to include the picture so that people will get the joke. :smile:

**Pull request merged**
