### PR TITLE
X3D responsive scaling

### PR DESCRIPTION
**Pull request by bmegli**
Thanks to @WasabiFan  for the suggestion (percentage width also on parent container).

This did the trick.

### CODE REVIEW

**Comment by WasabiFan** [comment]
Ugh, did LEGO _really_ break a bunch of links again? This is starting to get frustrating...

The CI server failures aren't an issue; I'll merge this now.

**Comment by bmegli** [comment]
Thanks!

**Comment by WasabiFan** [comment]
Wow, this actually works well on my phone too! Touch controls are pretty nice.
wp_ss_20160906_0001

**Comment by bmegli** [comment]
Yes! I have tried it also on some phones. With the responsive fix It looks good, the performance varies.

Strangely I am only having problems on one of my desktops.

**Pull request merged**
