### PR TITLE
stated that the Ev3 should be connected

### PR DESCRIPTION
**Pull request by moriarty**
The Ev3 should be connected to the host computer at some point before step 4, so I added a reminder in step 3.

### CODE REVIEW

**Comment by dlech** [comment]
Good idea. The `v` in `EV3` should be capitalized though.

**Comment by moriarty** [comment]
@dlech, I just fixed the capital V via the browser editor. If you prefer I squash the commits together let me know.

**Comment by dlech** [comment]
For a code repository, I  would say yes to squashing, but for the website, I don't really care.

**Comment by dlech** [comment]
Thanks!

**Pull request merged**
