### PR TITLE
Added Prolog API

### PR DESCRIPTION
**Pull request by maweki**
As per #414, added a (possibly incomplete) implementation written in Prolog.

### CODE REVIEW

**Comment by dlech** [comment]
Before I merge, I just wanted to make sure you put this in the *Out-of-date, abandoned and unfinished implementations* section on purpose. If this project is active, it should be moved up before *Vala, Genie and other GObject-based languages with ev3devKit*.

**Comment by maweki** [comment]
It is active and I even hope to find students to work on it further but it is incomplete. For example, there is no support for audio output, display, dc-motors, etc..

For the latter we did not have the available hardware to test this and for the former we did not have the (wo)manpower to implement it. I am happy to put it in the first category and I am happy to support the library for the foreseeable future but it is by no means complete. It has just enough features for our AI courses combining Prolog planning algorithms with actual robotics hardware.

You decide where it fits best. I am happy to move it.

**Comment by dlech** [comment]
If it runs on ev3dev-stretch and works with motors and at least a few sensors, I would call it good enough to bump up to the main list.

**Comment by maweki** [comment]
Thank you. It's good that it is on the homepage as I will be presenting this work on at least two (academic) conferences in Europe this year. I hope this finds some interest.

**Comment by dlech** [comment]
Merged, thanks!

**Pull request merged**
