### PR TITLE
Create 2020-07-17-Sioux.NET-on-Track.md

### PR DESCRIPTION
**Pull request by hansodenthal**
I would like to add my project to the Projects page.

### CODE REVIEW

**Comment by hansodenthal** [comment]
> 
> 
> Thanks for sharing. Can we get a copy of the image copied here so we don't have to worry about it breaking in the future?
> 
> Also, the file format is [markdown](https://guides.github.com/features/mastering-markdown/), so no HTML is needed.

Sorry, but I don't understand to what image you're referring. Can you please give more detail.

Hans

**Comment by dlech** [comment]
You should be able to upload it at https://github.com/hansodenthal/ev3dev.github.io/tree/patch-1/images/projects

**Comment by hansodenthal** [comment]
Done.

**Comment by hansodenthal** [comment]
What is the status of my request to have our project displayed?

**Comment by dlech** [comment]
merged, thanks!

https://www.ev3dev.org/projects/2020/07/17/Sioux.NET-on-Track/

**Comment by hansodenthal** [comment]
Thank you!

Regards, Hans

**Pull request merged**
