### PR TITLE
News post for Python library v2 beta

### PR DESCRIPTION
**Pull request by WasabiFan**

### CODE REVIEW

**Comment by dlech** [comment]
Looks good. Can we get a picture to go with it?

Also, I didn't go back to look but if there isn't a direct link to the ev3dev-stretch image downloads, we should add one.

**Comment by WasabiFan** [comment]
@dlech what picture would you suggest?  I'll be able to make changes in around 30min.

**Comment by dlech** [comment]
you could mash up the python logo and ev3dev logo

**Comment by WasabiFan** [comment]
OK, I'll try it out later today.

**Comment by WasabiFan** [comment]
image

image

**Comment by dlech** [comment]
Awesome. Thanks!

**Pull request merged**
