### PR TITLE
PIX3L PLOTT3R project added

### PR DESCRIPTION
**Pull request by droidsrobotics**
We added a project page for the PIX3L PLOTT3R.  Hope it looks right.  The content for the page and the YouTube video are done. We are still in the process of finishing the LDD for the design. We will add that soon, but there are pictures for the build on the project’s homepage.  Code has been shared using github. We will keep that updated.

### CODE REVIEW

**Comment by WasabiFan** [comment]
This is really cool! I think that's the best resolution I've seen on a LEGO-based printer of any sort.

**Comment by droidsrobotics** [comment]
Don't know why the checks are failing -- this is our first time with this type of pull request. It seems to be complaining about http://honk.sigxcpu.org/projects/git-buildpackage/manual-html/gbp.html. However, this is not something we changed.

**Comment by dlech** [comment]
It looks like there is a link broken somewhere else on the site that is causing the failure, so nothing to worry about here.

I've been following your progress of Facebook. Thanks for sharing here too.

**Comment by dlech** [comment]
http://www.ev3dev.org/projects/2016/02/26/PIX3L-PLOTT3R/

**Comment by rhempel** [comment]
Great job guys!

**Pull request merged**
