### PR TITLE
Add link to view ev3dev on GitHub

### PR DESCRIPTION
**Pull request by WasabiFan**

### CODE REVIEW

**Comment by dlech** [comment]
What is the benefit of this? Since there is not actually any code in the ev3dev/ev3dev repository, I think this would be misleading. And we already (should) have a direct link to the issues, which is really the only thing the ev3dev/ev3dev repository is used for besides release notes and hosting the downloads (which also has a direct link already).

**Comment by WasabiFan** [comment]
I generally agree -- there isn't much on the meta repo main page that's valuable. The main reasons that I had in mind were:
- Showing someone interested in the project that it _is_ on GitHub gives them a clear idea of how they can look into ev3dev
- Seeing the message in the README that we have a meta repo as well as many code repos explains why we don't have any other links to GitHub code
- If you want to find ev3dev stuff, GitHub is the place to look

In the end, it's just a minor addition that isn't very important -- if you don't think that it has value, I have no issue with you not merging it in.

Honestly, a better tactic would be to make sure that a prospective user has everything that they need on one site -- the latest download along with the release notes and getting started link would be shown on a "downloads" page, and we'd direct everyone there. But that's a lot more work than any of this deserves right now, so I decided I'd experiment with the "simple" approach :smile:.

P.S. I think adding this link is also partly a selfish attempt to make it easier for me to get to GitHub to check something after I follow a docs link that someone posts in an issue :wink:

**Comment by dlech** [comment]
I figured that was where you where coming from. 

What do you think about this instead? I am pretty sure that we have access to the GitHub "organization" info the [ev3dev organization](https://github.com/ev3dev) that includes being able to list all of the repositories. Assuming that is true, we could easily make a page that has all of the ev3dev repositories listed and it would not have to be manually maintained. We might want to make an exception for the flagship repositories like brickman, ev3devKit ev3dev.github.io and even the ev3dev meta repo. These could be listed first with a bit of an explanation.

**Comment by dlech** [comment]
Or maybe we fixup the readme in ev3dev/ev3dev with links to the other repositories. I kind of like this idea actually.

**Comment by WasabiFan** [comment]
Those both sound like good options. The "improve the readme" option is definitely the easiest, and can work in parallel with the other one, so I'd say we should get that done first. What do you think we should have in the readme? An explanation about the meta repo and then info about the other repos in the organization? Maybe with a quick summary of what ev3dev is?

A list of the repos on the website would be a great addition as well, and should be fairly simple to set up. I'll try it out and see how it looks.

P.S. It would be great to clean up the CSS on that website to remove all the "compatibility" junk that we don't really need (IE8 compat isn't something that benefits us much) and split it up into multiple files to make it easier to maintain and contribute to. I think I might do that as well.

**Comment by ddemidov** [comment]
Have you guys seen this: http://ben.balter.com/2015/06/11/using-github-pages-to-showcase-your-orgs-open-source-efforts/? Especially look at the list of examples in the last section.

**Comment by rhempel** [comment]
@WasabiFan - thnks for all of your work on making the site look and navigate better, and for offering to clean up the CSS. Also to @dlech for keeping a hand on the rudder of this part of the project as well as most others.

**Comment by WasabiFan** [comment]
> Have you guys seen this: http://ben.balter.com/2015/06/11/using-github-pages-to-showcase-your-orgs-open-source-efforts/?

That's exactly what we need -- GitHub provides a lot of metadata for the organization that the site is hosted from and its repos. From what I can tell, they also have info on the repo releases, download URLs, etc -- which means we should be able to provide a great "getting started experience".

I'll have to look at that in more detail to make sure that we can get at the repo releases from the organization page, but I'm sure I can figure it out. I've started working on a basic list, so I'll probably report back on my findings soon. Of course, if GitHub isn't willing to give me organization info from a local debug server, this could get interesting :wink:

**Pull request closed without merging**
